### ISSUE TITLE
Thanks for your great work, but I'm wondering there are to many unnecessary tensorboard summary writing.

### ISSUE THREAD

**Issue by rik-yo** [HudsonHuang/tensorflow-template#5]
In [main.py](https://github.com/HudsonHuang/tensorflow-template/blob/f06f441ecfa54b5b61bcfdcc3c3354f9d70a1fed/main.py#L153)
you called summary writer every step:
`
train_writer.add_summary(summary, epoch)
`
That made too many uncessary disk IO my notebook, and cause messy tensorboard logging.

**Comment by HudsonHuang** [comment]
Dear rik-yo,

Thanks for your advice, it is certainly an important preformance enhancement, I would fix it in later commits.

Cheers!

**Comment by HudsonHuang** [comment]
@rik-yo 
Dear rik-yo,
Thank you for noticing this issue. I have sovle this in the [#6 pull request](
https://github.com/HudsonHuang/tensorflow-template/pull/6) , so I am closing the issue.
